// Import the Anchor framework prelude — gives us #[program], #[derive(Accounts)],
// Context, Result, and all the core types we need. This is like importing
// OpenZeppelin's base contracts in Solidity.
use anchor_lang::prelude::*;

// Import Anchor's SPL token wrappers. These give us:
//   - `token::mint_to`   — CPI helper to mint tokens (like ERC-20 _mint)
//   - `token::transfer`  — CPI helper to transfer tokens (like ERC-20 transfer)
//   - `token::burn`      — CPI helper to burn tokens (like ERC-20 burn)
//   - `MintTo`, `Transfer`, `Burn` — CPI account structs for building the context
use anchor_spl::token::{self, Burn, Mint, MintTo, Token, TokenAccount, Transfer};

// Import the Associated Token Account program type.
// This program creates deterministic token accounts per (wallet, mint) pair.
// No EVM equivalent — in Solidity, balances just live in a mapping.
use anchor_spl::associated_token::AssociatedToken;

// Declare the program's on-chain address. Anchor uses this to verify the program ID
// at runtime. In Solidity, the contract address is assigned at deployment; here we
// hardcode it (generated by `anchor keys list`). This is a placeholder — replace with
// your actual program ID after deploying.
declare_id!("11111111111111111111111111111111");

// The #[program] macro marks this module as the Anchor program entry point.
// Each public function inside becomes an instruction that clients can call.
// In Solidity terms, this is the contract body with its external functions.
#[program]
pub mod token_operations {
    use super::*;

    // === Instruction 1: Create Token ===
    //
    // Solidity equivalent: deploying a new ERC-20 contract.
    //
    // In EVM, you'd run `new ERC20("MyToken", "MTK", 18)` to deploy a contract.
    // On Solana, we create a Mint Account — a data account that the Token Program
    // recognizes as a token definition. Anchor's `init` constraint on the mint
    // account in CreateToken handles the actual CPI to InitializeMint.
    //
    // Parameters:
    //   ctx      — the validated account context (see CreateToken struct below)
    //   decimals — number of decimal places (6 for stablecoins, 9 for typical Solana tokens)
    //
    // The decimals parameter is passed to the mint initialization via the
    // account constraint `mint::decimals = decimals` in the CreateToken struct.
    // We don't need to do anything in the function body because Anchor's `init`
    // constraint already performs the CPI to create and initialize the mint.
    pub fn create_token(ctx: Context<CreateToken>, decimals: u8) -> Result<()> {
        // Log the creation for debugging. Equivalent to emitting a Solidity event.
        msg!(
            "Token created! Mint: {}, Decimals: {}, Authority: {}",
            ctx.accounts.mint.key(),
            decimals,
            ctx.accounts.authority.key()
        );
        // Anchor already initialized the mint via the `init` constraint.
        // Nothing else to do — the mint exists on-chain after this instruction.
        Ok(())
    }

    // === Instruction 2: Mint Tokens ===
    //
    // Solidity equivalent: `_mint(to, amount)` inside an ERC-20.
    //
    // Creates new tokens out of thin air and deposits them into a Token Account.
    // Only the mint authority can do this — like an `onlyOwner` modifier on _mint.
    //
    // Parameters:
    //   ctx    — the validated account context (see MintTokens struct below)
    //   amount — number of tokens to mint (in smallest unit, like wei in Solidity)
    pub fn mint_tokens(ctx: Context<MintTokens>, amount: u64) -> Result<()> {
        // Build the CPI context for the Token Program's MintTo instruction.
        // This is analogous to building calldata for a Solidity low-level .call():
        //   - mint:      the Mint Account whose supply will increase
        //   - to:        the Token Account that will receive the new tokens
        //   - authority: the mint authority signer (must match mint.mint_authority)
        let cpi_accounts = MintTo {
            // The mint account to mint from. Its `supply` field will increase.
            // In Solidity, this is like modifying `totalSupply` in the ERC-20 contract.
            mint: ctx.accounts.mint.to_account_info(),
            // The destination token account. Its `amount` field will increase.
            // In Solidity, this is like `_balances[to] += amount`.
            to: ctx.accounts.token_account.to_account_info(),
            // The mint authority — must be a signer and must match the mint's
            // `mint_authority` field. Like requiring `msg.sender == owner` in Solidity.
            authority: ctx.accounts.authority.to_account_info(),
        };

        // Get a reference to the Token Program. We need to tell Anchor which program
        // to CPI into. On EVM, the runtime knows which contract to call; on Solana,
        // you must specify it explicitly.
        let cpi_program = ctx.accounts.token_program.to_account_info();

        // Build the CpiContext — Anchor's wrapper around invoke().
        // `CpiContext::new` is for regular signers (the authority signed the transaction).
        // If the authority were a PDA, we'd use `CpiContext::new_with_signer` instead.
        let cpi_ctx = CpiContext::new(cpi_program, cpi_accounts);

        // Execute the CPI. This calls the Token Program's MintTo instruction.
        // The `?` propagates any error (like Solidity's require/revert).
        token::mint_to(cpi_ctx, amount)?;

        // Log the operation for debugging and transaction history.
        msg!(
            "Minted {} tokens to {}",
            amount,
            ctx.accounts.token_account.key()
        );

        Ok(())
    }

    // === Instruction 3: Transfer Tokens ===
    //
    // Solidity equivalent: `transfer(to, amount)` in ERC-20.
    //
    // Moves tokens from one Token Account to another. The owner of the source
    // account must sign the transaction — like how `msg.sender` must own the
    // tokens in Solidity's `transfer`.
    //
    // Parameters:
    //   ctx    — the validated account context (see TransferTokens struct below)
    //   amount — number of tokens to transfer (smallest unit)
    pub fn transfer_tokens(ctx: Context<TransferTokens>, amount: u64) -> Result<()> {
        // Build the CPI context for Transfer.
        // In Solidity: `_balances[from] -= amount; _balances[to] += amount;`
        // On Solana, the Token Program does this atomically via CPI.
        let cpi_accounts = Transfer {
            // Source token account — balance will decrease.
            // Must be owned by `authority` (verified by the constraint below).
            from: ctx.accounts.from_ata.to_account_info(),
            // Destination token account — balance will increase.
            // Must be for the same mint as `from` (verified by constraints).
            to: ctx.accounts.to_ata.to_account_info(),
            // The owner of the source token account. Must sign the transaction.
            // In Solidity, this is implicit via `msg.sender`.
            authority: ctx.accounts.owner.to_account_info(),
        };

        // CPI into the Token Program.
        let cpi_program = ctx.accounts.token_program.to_account_info();
        let cpi_ctx = CpiContext::new(cpi_program, cpi_accounts);
        token::transfer(cpi_ctx, amount)?;

        msg!(
            "Transferred {} tokens from {} to {}",
            amount,
            ctx.accounts.from_ata.key(),
            ctx.accounts.to_ata.key()
        );

        Ok(())
    }

    // === Instruction 4: Burn Tokens ===
    //
    // Solidity equivalent: `burn(amount)` in ERC-20.
    //
    // Destroys tokens, removing them from a Token Account and decreasing
    // the Mint's total supply. The token owner must sign.
    //
    // Parameters:
    //   ctx    — the validated account context (see BurnTokens struct below)
    //   amount — number of tokens to burn (smallest unit)
    pub fn burn_tokens(ctx: Context<BurnTokens>, amount: u64) -> Result<()> {
        // Build the CPI context for Burn.
        // In Solidity: `_balances[msg.sender] -= amount; _totalSupply -= amount;`
        let cpi_accounts = Burn {
            // The mint whose supply will decrease.
            mint: ctx.accounts.mint.to_account_info(),
            // The token account to burn from. Its `amount` field will decrease.
            from: ctx.accounts.token_account.to_account_info(),
            // The owner of the token account. Must sign.
            authority: ctx.accounts.owner.to_account_info(),
        };

        let cpi_program = ctx.accounts.token_program.to_account_info();
        let cpi_ctx = CpiContext::new(cpi_program, cpi_accounts);
        token::burn(cpi_ctx, amount)?;

        msg!(
            "Burned {} tokens from {}",
            amount,
            ctx.accounts.token_account.key()
        );

        Ok(())
    }
}

// =============================================================================
// Account Validation Structs
// =============================================================================
//
// In Solidity, the EVM handles storage layout and access control implicitly.
// On Solana, we must declare every account an instruction needs and specify
// constraints that Anchor validates before the instruction runs.
//
// Think of these as the function signature + require() checks combined.

// === Accounts for create_token ===
//
// Creates a new Mint Account. Equivalent to deploying an ERC-20 contract.
//
// Required accounts:
//   - mint:             the new Mint Account to create (Keypair, signer)
//   - authority:        wallet that will be the mint/freeze authority + payer
//   - system_program:   needed to create the account (allocate space, transfer lamports)
//   - token_program:    the SPL Token Program that initializes the mint
//   - rent:             sysvar for rent exemption calculation
#[derive(Accounts)]
#[instruction(decimals: u8)]
pub struct CreateToken<'info> {
    // The mint account to create. `init` tells Anchor to:
    //   1. Allocate space for a Mint (82 bytes)
    //   2. Transfer enough lamports for rent exemption from `authority`
    //   3. CPI to Token Program's InitializeMint with the specified params
    //
    // `mint::decimals = decimals` passes the function arg to InitializeMint.
    // `mint::authority = authority` sets who can mint new tokens.
    // `mint::freeze_authority = authority` sets who can freeze token accounts.
    //
    // In Solidity, all of this happens in the ERC-20 constructor.
    #[account(
        init,
        payer = authority,
        mint::decimals = decimals,
        mint::authority = authority,
        mint::freeze_authority = authority,
    )]
    pub mint: Account<'info, Mint>,

    // The wallet creating the token. Pays for account creation and becomes
    // both the mint authority and freeze authority.
    // `mut` because lamports will be deducted for rent.
    // In Solidity, this would be `msg.sender` in the constructor.
    #[account(mut)]
    pub authority: Signer<'info>,

    // The System Program — required for creating new accounts (allocating space).
    // In Solidity, the EVM handles account/storage creation implicitly.
    pub system_program: Program<'info, System>,

    // The SPL Token Program — required for initializing the mint.
    // This is the shared program that manages ALL SPL tokens.
    pub token_program: Program<'info, Token>,
}

// === Accounts for mint_tokens ===
//
// Mints new tokens into a Token Account. Equivalent to ERC-20 `_mint(to, amount)`.
//
// Required accounts:
//   - mint:            the Mint Account (supply will increase)
//   - token_account:   the recipient's Token Account (balance will increase)
//   - authority:       the mint authority (must sign)
//   - token_program:   the SPL Token Program
#[derive(Accounts)]
pub struct MintTokens<'info> {
    // The mint to mint from. Must be mutable because `supply` will increase.
    //
    // No additional constraint needed here — the Token Program itself will verify
    // that `authority` matches `mint.mint_authority` during the CPI. However,
    // marking it `mut` tells Anchor the account data will change.
    #[account(mut)]
    pub mint: Account<'info, Mint>,

    // The token account to receive minted tokens. Must be:
    //   - Mutable (balance will increase)
    //   - Associated with the correct mint (verified by `token::mint = mint`)
    //
    // `token::mint = mint` ensures no one can pass a token account for a different
    // token. In Solidity, this check is implicit (balances are per-contract).
    #[account(
        mut,
        token::mint = mint,
    )]
    pub token_account: Account<'info, TokenAccount>,

    // The mint authority. Must sign the transaction.
    // The Token Program will verify this matches `mint.mint_authority`.
    // In Solidity: `require(msg.sender == owner)`.
    #[account(mut)]
    pub authority: Signer<'info>,

    // The SPL Token Program to CPI into.
    pub token_program: Program<'info, Token>,
}

// === Accounts for transfer_tokens ===
//
// Transfers tokens between two Token Accounts. Equivalent to ERC-20 `transfer(to, amount)`.
//
// Required accounts:
//   - mint:            the Mint Account (for validation only, not modified)
//   - from_ata:        sender's Token Account (balance will decrease)
//   - to_ata:          receiver's Token Account (balance will increase)
//   - owner:           owner of the source token account (must sign)
//   - token_program:   the SPL Token Program
#[derive(Accounts)]
pub struct TransferTokens<'info> {
    // The mint this transfer is for. Not mutated, but passed for validation.
    // Both from_ata and to_ata must be for this mint.
    pub mint: Account<'info, Mint>,

    // Source token account — tokens will be debited from here.
    // Constraints ensure:
    //   - It's for the correct mint (`token::mint = mint`)
    //   - The signer owns it (`token::authority = owner`)
    //
    // In Solidity, these checks happen inside `transfer()`:
    //   `require(_balances[msg.sender] >= amount)`
    //   and the mapping key IS msg.sender, so ownership is implicit.
    #[account(
        mut,
        token::mint = mint,
        token::authority = owner,
    )]
    pub from_ata: Account<'info, TokenAccount>,

    // Destination token account — tokens will be credited here.
    // Must be for the same mint. We don't check authority because anyone
    // can receive tokens (like how anyone can be a `to` in ERC-20 transfer).
    #[account(
        mut,
        token::mint = mint,
    )]
    pub to_ata: Account<'info, TokenAccount>,

    // The owner of the source token account. Must sign.
    // In Solidity, this is `msg.sender`.
    pub owner: Signer<'info>,

    // The SPL Token Program.
    pub token_program: Program<'info, Token>,
}

// === Accounts for burn_tokens ===
//
// Burns tokens from a Token Account. Equivalent to ERC-20 `burn(amount)`.
//
// Required accounts:
//   - mint:           the Mint Account (supply will decrease)
//   - token_account:  the Token Account to burn from (balance will decrease)
//   - owner:          owner of the token account (must sign)
//   - token_program:  the SPL Token Program
#[derive(Accounts)]
pub struct BurnTokens<'info> {
    // The mint whose supply will decrease. Must be mutable.
    #[account(mut)]
    pub mint: Account<'info, Mint>,

    // The token account to burn from. Must be:
    //   - For the correct mint
    //   - Owned by the signer
    //   - Mutable (balance will decrease)
    //
    // In Solidity: `_balances[msg.sender] -= amount; _totalSupply -= amount;`
    #[account(
        mut,
        token::mint = mint,
        token::authority = owner,
    )]
    pub token_account: Account<'info, TokenAccount>,

    // The token account owner. Must sign to authorize the burn.
    pub owner: Signer<'info>,

    // The SPL Token Program.
    pub token_program: Program<'info, Token>,
}
